
---
- name: Install Nginx and Node.js, Configure Nginx, Set ENVIRONMENT_NAME variable, Install dependencies, and Start application
  hosts: ecf5-instance-prod
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Install Node.js
      apt:
        name: nodejs
        state: latest

    - name: Copy Nginx configuration file
      copy:
        src: nginx.conf
        dest: /etc/nginx/conf.d/default.conf
      notify: restart nginx

    - name: Configure Nginx
      copy:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Install dependencies
      apt:
        name: npm
        state: latest

    - name: Install dotenv
      npm:
        name: dotenv
        path: /opt/myapp

    - name: Create .env file and add ENVIRONMENT_NAME variable
      copy:
        content: "ENVIRONMENT_NAME=production\n"
        dest: /opt/myapp/.env
        owner: root
        group: root
        mode: '0644'

    - name: Copy app.js
      copy:
        src: app.js
        dest: /opt/myapp/
        owner: root
        group: root
        mode: '0644'

    - name: Create Node.js service
      become: true
      copy:
        content: |
          [Unit]
          Description=Node.js Server
          After=network.target
          [Service]
          User=root
          Group=root
          WorkingDirectory=/opt/myapp
          ExecStart=/usr/bin/node /opt/myapp/app.js
          Restart=always
          Environment=NODE_ENV=production
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/myapp.service
      notify: restart myapp

    - name: Start Node.js service
      systemd:
        name: myapp
        state: started
        enabled: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart myapp
      systemd:
        name: myapp
        state: restarted
        
        
